architectury {
    platformSetupLoomIde()
    fabric()
}

fabricApi {
    configureDataGeneration {
        createSourceSet = false
        addToResources = false
        outputDirectory = project(':common').file('src/generated/resources')
    }
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

dependencies {
    implementation libs.fabric.loader
    implementation libs.fabric.api
    implementation libs.jamlib.fabric

    common(project(':common')) { transitive false }
}
