plugins {
    id 'com.gradleup.shadow' version '8.3.3'
    id 'me.shedaniel.unified-publishing'
}

architectury {
    platformSetupLoomIde()
    fabric()
}

base {
    archivesName = 'rightclickharvest-fabric'
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

dependencies {
    implementation libs.fabric.loader
    implementation libs.fabric.api
    implementation libs.jamlib.fabric
    runtimeOnly libs.modmenu

    common(project(':common')) { transitive false }
    shadowCommon(project(path: ':common', configuration: 'transformProductionFabric')) { transitive false }
}

if (System.getenv('CURSEFORGE_API_KEY') != null && System.getenv('MODRINTH_API_KEY') != null) {
    unifiedPublishing {
        project {
            displayName = "V${project.version} (Fabric ${project.minecraft_version})"
            changelog = rootProject.file('CHANGELOG.md').text
            releaseType = project.version.contains('beta') ? 'beta' : 'release'
            gameVersions = [project.minecraft_version, *(project.additional_minecraft_versions == '' ? [] : project.additional_minecraft_versions.split(','))]
            gameLoaders = ['fabric', 'quilt']

            mainPublication tasks.shadowJar

            relations {
                depends {
                    curseforge = 'fabric-api'
                    modrinth = 'fabric-api'
                }

                depends {
                    curseforge = 'jamlib'
                    modrinth = 'jamlib'
                }
            }

            curseforge {
                token = System.getenv('CURSEFORGE_API_KEY')
                id = '452834'
            }

            modrinth {
                token = System.getenv('MODRINTH_API_KEY')
                id = 'Cnejf5xM'
            }
        }
    }
}

configurations {
    apiElements {
        outgoing.artifacts.clear()
        outgoing.artifact(shadowJar)
    }
    runtimeElements {
        outgoing.artifacts.clear()
        outgoing.artifact(shadowJar)
    }
}

publishing {
    publications {
        mavenFabric(MavenPublication) {
            artifactId = rootProject.base.archivesName.get() + '-fabric'
            from components.java
        }
    }

    repositories {
        if (System.getenv('MAVEN_USERNAME') != null && System.getenv('MAVEN_PASSWORD') != null) {
            maven {
                url = 'https://maven.jamalam.tech/releases'
                credentials {
                    username = System.getenv('MAVEN_USERNAME')
                    password = System.getenv('MAVEN_PASSWORD')
                }
            }
        }
    }
}


processResources {
    processResources {
        def substitutions = [
                'version'             : project.version,
                'minecraft_version'   : project.minimum_minecraft_version,
                'fabric_api_version'  : project.minimum_fabric_api_version,
                'jamlib_version'      : project.minimum_jamlib_version
        ]

        filesMatching('fabric.mod.json') {
            expand substitutions
        }

        substitutions.each { inputs.property it.key, it.value }
    }
}

jar {
    archiveClassifier = 'raw'
}

shadowJar {
    dependsOn(jar)
    mainSpec.sourcePaths.clear()
    from(zipTree(jar.archiveFile))

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = null
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

sourcesJar {
    def commonSources = project(':common').sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}
