architectury {
    platformSetupLoomIde()
    fabric()
}

loom {
    runs {
        gametest {
            server()
            name 'Game Test'
            vmArg '-Dfabric-api.gametest'
        }

        gametestClient {
            client()
            name 'Game Test Client'
            vmArg '-Dfabric-api.gametest'
        }
    }
}

configurations {
    common
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

dependencies {
    implementation libs.fabric.loader
    implementation libs.fabric.api
    implementation libs.jamlib.fabric

    implementation project(':fabric')
//    implementation project(':common')
    common(project(':common')) { transitive false }
}
