org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
version=4.6.2+26.1.x
minecraft_version=26.1.2

additional_minecraft_versions=26.1,26.1.1
minimum_minecraft_version=26.1
minimum_fabric_api_version=0.146.1+26.1.2
minimum_jamlib_version=2.0.0+26.1.x

branch=26.1
group=io.github.jamalam360
mod_name=Right Click Harvest
mod_id=rightclickharvest
enabled_platforms=fabric,neoforge

systemProp.javax.xml.parsers.SAXParserFactory=com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl
systemProp.javax.xml.transform.TransformerFactory=com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl
systemProp.javax.xml.parsers.DocumentBuilderFactory=com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl
