org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
version=4.6.2+26.3.x
minecraft_version=26.3

additional_minecraft_versions=
minimum_minecraft_version=26.3
minimum_fabric_api_version=0.160.7+26.3
minimum_jamlib_version=2.3.1+26.3.x

branch=main
group=io.github.jamalam360
mod_name=Right Click Harvest
mod_id=rightclickharvest
enabled_platforms=fabric,neoforge

systemProp.javax.xml.parsers.SAXParserFactory=com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl
systemProp.javax.xml.transform.TransformerFactory=com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl
systemProp.javax.xml.parsers.DocumentBuilderFactory=com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl
