[versions]
# https://projects.neoforged.net/neoforged/neoforge
neoforge = "26.1.2.29-beta"

# https://fabricmc.net/develop
fabric-loader = "0.19.2"
fabric-api = "0.146.1+26.1.2"

# https://maven.jamalam.tech/#/releases
jamlib = "2.0.0+26.1.x"

# https://modrinth.com/mod/modmenu/versions
modmenu = "18.0.0-alpha.8"

[libraries]
neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }

fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

jamlib-common = { module = "io.github.jamalam360:jamlib", version.ref = "jamlib" }
jamlib-fabric = { module = "io.github.jamalam360:jamlib-fabric", version.ref = "jamlib" }
jamlib-neoforge = { module = "io.github.jamalam360:jamlib-neoforge", version.ref = "jamlib" }

modmenu = { module = "maven.modrinth:modmenu", version.ref = "modmenu" }
