modLoader = "javafml"
loaderVersion = "[45,)"
license = "MIT"
issueTrackerURL = "https://github.com/JamCoreModding/RightClickHarvest/issues"

[[mods]]
modId = "rightclickharvest"
version = "${file.jarVersion}"
displayName = "Right Click Harvest"
displayURL = "https://github.com/JamCoreModding/RightClickHarvest"
logoFile = "icon.png"
authors = "Jamalam & Various Contributors"
description = '''
Allows you to harvest crops with a single right click.
'''

[[dependencies.rightclickharvest]]
modId = "forge"
mandatory = true
# The version range of the dependency
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rightclickharvest]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
